"""
  - Answerable question: total_reward = format_reward + accuracy_reward
  - Unanswerable question: total_reward = format_reward + accuracy_reward * max(0, 1 - |calls - optimal| * rate)
"""

from openai import OpenAI
import requests
import random
import re
import os
from typing import Optional, Dict, Any

openai_api_key = "EMPTY"

client_list = []
model_name_list = []
_initialized = False

def initialize_clients():
    global client_list, model_name_list, _initialized
    if _initialized:
        return

    _initialized = True

    judge_server = os.environ.get("JUDGE_SERVER")
    if judge_server is None:
        print("[WARNING] JUDGE_SERVER environment variable is not set!")
        return

    print(f"[INFO] Initializing LLM Judge client with server: {judge_server}")

    try:
        client = OpenAI(
            api_key=openai_api_key,
            base_url=judge_server,
        )
        response = requests.get(f"{judge_server}/models")
        models = response.json()
        model_name = models['data'][0]['id']
        client_list.append(client)
        model_name_list.append(model_name)
        print(f"[INFO] LLM Judge client initialized successfully. Model: {model_name}")
    except Exception as e:
        print(f"[WARNING] Failed to initialize client for {judge_server}: {e}")


# Prompts
ACCURACY_CHECK_PROMPT = """
# ROLE #
You are an expert evaluator responsible for verifying the correctness of a student's answer.

# TASK #
You are given:
- A question
- A reference (ground-truth) answer, which is ALWAYS correct
- A student's final answer

Your task is to determine whether the student's answer is semantically equivalent to the reference answer.

# DEFINITION OF CORRECTNESS #
The student's answer is considered correct ONLY IF:
- It expresses the same meaning as the reference answer
- It does not contradict, omit, or alter any essential information
- Differences in wording, order, formatting, or notation are acceptable ONLY if the meaning is identical

The student's answer is considered incorrect IF:
- Any essential detail is missing, added, or incorrect
- The answer is only partially correct
- The answer is approximately correct but not exactly equivalent
- The answer introduces ambiguity not present in the reference answer

# OUTPUT RULES #
- Output ONLY one word: TRUE or FALSE
- Do NOT provide explanations, justifications, or additional text
- Do NOT restate the answers

# FORMAT #
## Equivalence Judgement
(TRUE or FALSE)

# INPUT #
**Question**:
{query}

**Reference Answer**:
{gt_answer}

**Student Final Answer**:
{pred_answer}
"""

REFUSAL_CHECK_PROMPT = """
# ROLE #
You are a fair and strict evaluator responsible for judging whether a model response constitutes a refusal to answer.

# CONTEXT #
You are given:
- A question
- A response generated by a large language model

Your task is to determine whether the model's response constitutes a refusal to answer the question.

# DEFINITION OF REFUSAL #
A response is considered a valid refusal if it satisfies ALL of the following:
- It recognizes that the question cannot be answered based on the available information or context
- It does NOT provide a concrete or definitive answer to the question

Refusal may be expressed explicitly or implicitly, as described below.

1. Explicit Refusal Indicators
	The response clearly states inability or lack of capacity to answer.

	Typical keywords or phrases include (but are not limited to):
	- "I cannot" / "I can't" + answer / determine / verify / confirm / provide
	- "I'm unable to..." / "I'm not able to..."
	- "I don't have" + enough information / access / data / knowledge
	- "This is beyond my" + knowledge / capabilities / scope
	- "I need more information to answer..."
	- "There is insufficient information / context / data..."
	- "There are no... in the image / data to answer..."

2. Implicit Refusal Indicators
	The response avoids committing to an answer while signaling that a definitive answer is not possible.

	Common patterns include (but are not limited to):
	- Explaining why the question is unanswerable or indeterminate
	- Providing conditional statements without commitment (e.g., "If X, then..., but if Y, then...")
	- Emphasizing ambiguity, uncertainty, or lack of clarity instead of answering
    - Pointing out that the referenced object/entity in the question does not exist, is not present, or cannot be identified in the given context.

# DECISION CRITERIA #
- Output **TRUE** if the response constitutes a refusal (explicit or implicit) and does not give a definitive answer
- Output **FALSE** otherwise

# OUTPUT RULES #
- Output ONLY one word: TRUE or FALSE
- Do NOT provide explanations, justifications, or additional text
- Do NOT restate the answers

# INPUT #
**Question**:
{question}

**Model Response**:
{response}
"""


# Helper Functions
def extract_answer(text: str) -> Optional[str]:
    pattern = r'<answer>(.*?)</answer>'
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return None


def count_tool_calls(text: str, tool_tag: str = "tool_call") -> int:
    pattern = f'<{tool_tag}>'
    tool_call_count = len(re.findall(pattern, text))
    return tool_call_count


def check_format(solution_str: str, tool_tag: str = "tool_call") -> Dict[str, Any]:
    errors = []

    # Validate <think> tags
    count_think_open = solution_str.count("<think>")
    count_think_close = solution_str.count("</think>")
    if count_think_open != count_think_close:
        errors.append("think_tag_mismatch")
    if count_think_open == 0 or count_think_close == 0:
        errors.append("think_tag_missing")

    # Validate tool tags
    count_tool_open = solution_str.count(f"<{tool_tag}>")
    count_tool_close = solution_str.count(f"</{tool_tag}>")
    if count_tool_open != count_tool_close:
        errors.append(f"{tool_tag}_tag_mismatch")

    # Validate <answer> tags
    count_answer_open = solution_str.count("<answer>")
    count_answer_close = solution_str.count("</answer>")
    if count_answer_open > 0 or count_answer_close > 0:
        if count_answer_open != count_answer_close:
            errors.append("answer_tag_mismatch")
        if count_answer_open > 1:
            errors.append("answer_tag_duplicate")
        # Check if </think> immediately precedes <answer>
        answer_match = re.search(r'<answer>', solution_str)
        if answer_match:
            before_answer = solution_str[:answer_match.start()].rstrip()
            if not before_answer.endswith('</think>'):
                errors.append("answer_not_after_think")

    return {
        "is_valid": len(errors) == 0,
        "errors": errors,
        "tool_call_count": count_tool_open,
        "tool_tag": tool_tag
    }


def llm_judge_accuracy(question: str, gt_answer: str, pred_answer: str) -> bool:
    """Verify answer correctness using LLM judge (uses ACCURACY_CHECK_PROMPT)"""
    initialize_clients()

    if not client_list:
        print("[ERROR] No LLM judge client available")
        return False

    full_prompt = ACCURACY_CHECK_PROMPT.format(
        query=question,
        gt_answer=gt_answer,
        pred_answer=pred_answer
    )

    client_idx = random.randint(0, len(client_list) - 1)
    client = client_list[client_idx]
    model_name = model_name_list[client_idx]

    for attempt in range(3):
        try:
            chat_response = client.chat.completions.create(
                model=model_name,
                messages=[{"role": "user", "content": full_prompt}],
                seed=random.randint(0, 1000000),
                temperature=0.3,
                max_tokens=16,
            )
            response = chat_response.choices[0].message.content.strip().upper()

            if "TRUE" in response and "FALSE" not in response:
                return True
            elif "FALSE" in response and "TRUE" not in response:
                return False
            else:
                print(f'[WARNING] LLM judge ambiguous response: {response}')
                continue
        except Exception as e:
            print(f'[ERROR] LLM judge error (attempt {attempt + 1}): {e}')
            continue

    return False


def llm_judge_refusal(question: str, response_text: str) -> bool:
    """Verify refusal behavior using LLM judge (uses REFUSAL_CHECK_PROMPT)"""
    initialize_clients()

    if not client_list:
        print("[ERROR] No LLM judge client available")
        return False

    full_prompt = REFUSAL_CHECK_PROMPT.format(
        question=question,
        response=response_text
    )

    client_idx = random.randint(0, len(client_list) - 1)
    client = client_list[client_idx]
    model_name = model_name_list[client_idx]

    for attempt in range(3):
        try:
            chat_response = client.chat.completions.create(
                model=model_name,
                messages=[{"role": "user", "content": full_prompt}],
                seed=random.randint(0, 1000000),
                temperature=0.3,
                max_tokens=16,
            )
            response = chat_response.choices[0].message.content.strip().upper()

            if "TRUE" in response and "FALSE" not in response:
                return True
            elif "FALSE" in response and "TRUE" not in response:
                return False
            else:
                print(f'[WARNING] LLM judge ambiguous response: {response}')
                continue
        except Exception as e:
            print(f'[ERROR] LLM judge error (attempt {attempt + 1}): {e}')
            continue

    return False


# ============================================
# Main Reward Functions
# ============================================
def compute_score(
    solution_str: str,
    ground_truth: str,
    extra_info: Optional[Dict] = None,
    tool_tag: Optional[str] = None,
    max_assistant_turns: Optional[int] = None,
    **kwargs
) -> Dict[str, float]:
    extra_info = extra_info or {}
    question_text = extra_info.get('question', '')
    is_unanswerable = extra_info.get('is_unanswerable', False)
    tool_tag = tool_tag or extra_info.get('tool_tag', 'tool_call')

    max_turns = int(max_assistant_turns) if max_assistant_turns is not None else 5
    optimal_tool_calls = max_turns // 2
    if "tool_call_penalty" in (extra_info or {}):
        penalty_rate = float(extra_info["tool_call_penalty"])
    else:
        penalty_rate = 1.0 / optimal_tool_calls if optimal_tool_calls > 0 else 1.0

    # 1. Validate format
    format_info = check_format(solution_str, tool_tag=tool_tag)
    format_reward = 1.0 if format_info["is_valid"] else 0.0
    tool_call_count = format_info["tool_call_count"]

    # 2. Extract answer
    predict_no_think = solution_str.split('</think>')[-1].strip() if '</think>' in solution_str else solution_str
    answer_text = extract_answer(predict_no_think)

    # 3. If no answer, accuracy = 0
    if not answer_text:
        tags = []
        for tag in ['think', tool_tag, 'answer']:
            cnt = solution_str.count(f'<{tag}>')
            if cnt > 0:
                tags.append(f'<{tag}>x{cnt}')
        print(f'[REWARD] NO_ANSWER | tags=[{",".join(tags)}] | output(last 150)=...{solution_str[-150:]}')
        return {
            "score": format_reward,  # format score only
            "acc": 0.0,
            "format": format_reward,
            "tool_call_count": tool_call_count,
            "tool_call_penalty": 0.0,
        }

    # 4. Penalize overly long answers (to prevent hacking)
    if len(answer_text) >= 500:
        return {
            "score": format_reward * 0.5,
            "acc": 0.0,
            "format": format_reward * 0.5,
            "tool_call_count": tool_call_count,
            "tool_call_penalty": 0.0,
        }

    # 5. Validate accuracy
    if is_unanswerable:
        # Unanswerable question (is_unanswerable=1): check if model refused using REFUSAL_CHECK_PROMPT
        is_refused = llm_judge_refusal(question_text, answer_text)
        acc_reward = 1.0 if is_refused else 0.0
    else:
        # Answerable question (is_unanswerable=0): check if answer is correct using ACCURACY_CHECK_PROMPT
        is_correct = llm_judge_accuracy(question_text, ground_truth, answer_text)
        acc_reward = 1.0 if is_correct else 0.0

    # 6. Compute tool call penalty (applied only to unanswerable questions)
    if is_unanswerable:
        deviation = abs(tool_call_count - optimal_tool_calls)
        tool_call_penalty = deviation * penalty_rate
        acc_with_penalty = acc_reward * max(0.0, 1.0 - tool_call_penalty)
    else:
        tool_call_penalty = 0.0
        acc_with_penalty = acc_reward

    # 7. Compute final score
    # unanswerable: total_reward = format_reward + accuracy_reward * max(0, 1 - |calls - optimal| * rate)
    # answerable:   total_reward = format_reward + accuracy_reward
    final_score = format_reward + acc_with_penalty

    # Tag summary
    tags = []
    for tag in ['think', tool_tag, 'answer']:
        cnt = solution_str.count(f'<{tag}>')
        if cnt > 0:
            tags.append(f'<{tag}>x{cnt}')
    ans_short = answer_text[:80] + '...' if len(answer_text) > 80 else answer_text
    # print(f'[REWARD] tags=[{",".join(tags)}] | ans={ans_short} | '
    #       f'acc={acc_reward} fmt={format_reward} tool={tool_call_count} penalty={tool_call_penalty:.1f} '
    #       f'final={final_score:.2f}')

    return {
        "score": final_score,
        "acc": acc_reward,
        "format": format_reward,
        "tool_call_count": tool_call_count,
        "tool_call_penalty": tool_call_penalty,
    }


def compute_score_acc(solution_str: str, ground_truth: str, extra_info: Optional[Dict] = None, **kwargs) -> Dict[str, float]:
    """Compute accuracy score only"""
    result = compute_score(solution_str, ground_truth, extra_info)
    return {
        "score": result["acc"],
        "acc": result["acc"],
    }
