"""
Convert dataset to VeRL training format for DeepEyesV2 model.

Input format (e.g., HARDBench):
    {
        "question": "...",
        "answer": "...",
        "image": "TallyQA/VG_100K/2360883.jpg",   # relative path from image_root
        "data_source": "tallyqa",
        "is_unanswerable": false
    }

Usage:
    python scripts/convert_deepeyesv2.py \
        --input /path/to/data.json \
        --output /path/to/output.json \
        --image_root /workspace/data/Dataset

    # Override prompts if needed:
        --system_prompt "Your custom system prompt"
        --user_template "Your custom user template with {question} placeholder"
"""

import json
import argparse

DEFAULT_SYSTEM_PROMPT = """You are an agent - please keep going until the user's query is completely resolved, before ending your turn and yielding back to the user. Only terminate your turn when you are sure that the problem is solved.

Solve the following problem step by step. In your reasoning process, if the answer cannot be determined, you can write Python code in a Jupyter Notebook to process the image and extract more information from it. The stdout and stderr content, along with the images generated by `plt.show()` will be returned to better assist with the user query.

You MUST use the python tool to analyze or transform images whenever it could improve your understanding. This includes but is not limited to zooming in, rotating, adjusting contrast, computing statistics, or isolating features.

You MUST plan extensively before each function call, and reflect extensively on the outcomes of the previous function calls. DO NOT do this entire process by making function calls only, as this can impair your ability to solve the problem and think insightfully.

For all the provided images, in order, the i-th image has already been read into the global variable "image_i" using the "PIL.Image.open()" function. For example, the first image can be accessed as "image_1". When writing Python code, you can directly use these variables without needing to read them again.

Your python code should be enclosed within <code> </code> tag.

Example for calling Python code in Jupyter Notebook:
<code>
```python
# python code here
```
</code>

Note:
1. **python** can be called to analyze the image. **python** will respond with the output of the execution or time out after 300.0 seconds.
2. Like jupyter notebook, you can use Python code to process the input image and use `plt.show()` to visualize processed images in your code.
3. All python code are running in the same jupyter notebook kernel, which means the functions and variables are automatically stored after code execution.
4. You program should always returns in finite time. Do not write infinite loop in your code.
5. Writing file to disk is not allowed.
"""

DEFAULT_USER_TEMPLATE = """<image>
{question}


You must put your answer inside <answer> </answer> tags, i.e., <answer> answer here </answer>. Please reason step by step. Use Python code to process the image if necessary. Format strictly as <think> </think> <code> </code> (if code is needed) or <think> </think> <answer> </answer>."""


def convert(input_path, output_path, image_root, system_prompt, user_template):
    with open(input_path) as f:
        data = json.load(f)

    converted = []
    for item in data:
        image_path = f"{image_root}/{item['image']}"
        user_content = user_template.format(question=item['question'])
        prompt = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ]
        entry = {
            "images": [{"image": image_path}],
            "data_source": item['data_source'],
            "prompt": prompt,
            "reward_model": {
                "ground_truth": str(item['answer']),
                "style": "rule",
            },
            "env_name": "deepeyes_v2",
            "extra_info": {
                "answer": str(item['answer']),
                "question": item['question'],
                "is_unanswerable": item['is_unanswerable'],
            },
        }
        converted.append(entry)

    with open(output_path, 'w') as f:
        json.dump(converted, f, indent=2, ensure_ascii=False)

    n_ans = sum(1 for x in converted if not x['extra_info']['is_unanswerable'])
    n_unans = sum(1 for x in converted if x['extra_info']['is_unanswerable'])
    print(f"Converted {len(converted)} entries → {output_path}")
    print(f"  Answerable: {n_ans}, Unanswerable: {n_unans}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', required=True, help='Input JSON file path')
    parser.add_argument('--output', required=True, help='Output JSON file path')
    parser.add_argument('--image_root', default='/workspace/data/Dataset',
                        help='Root path prepended to image relative paths')
    parser.add_argument('--system_prompt', default=None)
    parser.add_argument('--user_template', default=None,
                        help='User prompt template with {question} placeholder')
    args = parser.parse_args()

    convert(
        args.input, args.output, args.image_root,
        system_prompt=args.system_prompt or DEFAULT_SYSTEM_PROMPT,
        user_template=args.user_template or DEFAULT_USER_TEMPLATE,
    )
